runtime: python37
entrypoint: gunicorn -b :$PORT wishlist.wsgi

handlers:
- url: /static
  static_dir: www/static

- url: /.*
  script: auto

env_variables: 
  TRAVELER_PW: Capstone!! 

beta_settings:
  cloud_sql_instances: wishlist-django-385506:us-central1:wishlist-db